#! /bin/bash
#############################
#author:wanghai
#############################

echo -en "\033[35m"

for tmp in `ls`
do
    if [ -d $tmp -a -e $tmp/.git/config ];then
        echo "-------- $tmp -------"
        cd $tmp
        echo "convert '10.92.11.203' to '10.92.11.178' "
        sed -i 's/10.92.11.203/10.92.11.178/' .git/config
        cd -
        echo
    fi
done

echo -en "\033[0m"

