#! /bin/sh -

#######################################
# Author: hai.wang 
#######################################
usage () {
    echo "\033[34m"
    echo "Usage:"
    echo "$0  --> output.tgz"
    echo "\033[0m"
}
tar_git_startus () {
echo "############files to be tar############"
TMP=`mktemp`
if [ ! -f $TMP ];then
    echo mktemp failed
    exit 1
fi

#######################################

for i in $(git status .| awk -F " " '{print $NF}');do 
    #    echo "$i tttt"
    if [ -e $i -a $i != output.tgz ];then
        echo $i>>$TMP
    fi
done

#######################################

a=$1
OUTFILE=${a:='output.tgz'}

if [ -f $OUTFILE ];then
    rm $OUTFILE
fi

cat $TMP | xargs tar cvzf $OUTFILE --exclude=$OUTFILE
rm $TMP

echo "#######################################"
echo "tar all file to $OUTFILE"
}

if [ $# -gt 0 ]; then
    usage
else
		tar_git_startus 
fi
