#! /bin/sh -

#######################################
# Author: hai.wang 
#######################################
usage () {
    echo -en "\033[34m"
    echo "Usage:"
    echo "$0 commit_num output.tgz"
    echo -en "\033[0m"
}

tar_git_show () {

	
	if [ ! -e ./.git ]; then
		echo "To execute this command in the git-top-level directory"
		exit 1
	fi

	Data=`date +%Y-%m-%d-%H-%M-%S`
	TMP=~/$Data
	touch $TMP
	if [ ! -f $TMP ];then
	    echo "Create tmp file failed!"
	    exit 1
	fi
	
	#####################################
	a=$1
	COMMIT_NUM=$a
	for i in $(git show $COMMIT_NUM --name-only);do
	    if [ -f $i ];then
	        echo $i>>$TMP
	    fi
	done
	
	###################################
    #echo "para is $#"
    if [ $# -eq 1 ];then
        git show $COMMIT_NUM > output.patch
        echo "Generate patch is output.patch"
    else
        echo "Generate patch is $2.patch"
        git show $COMMIT_NUM > $2.patch
	    b=$2.tgz
    fi
	OUTFILE=${b:='output.tgz'}
	
	if [ -f $OUTFILE ];then
	    rm $OUTFILE
	fi

	echo "############files to be tar############"
	cat $TMP | xargs tar cvfz $OUTFILE --exclude=$OUTFILE
	rm $TMP
	
	echo "#######################################"
	echo "tar all file to $OUTFILE"

}

if [ $# -eq 0 ]; then
    usage
else
		tar_git_show $1 $2
fi
